/**
 * NapicuWebAPI
 * NapicuAPI pro NapicuWebs
 *
 * The version of the OpenAPI document: v2.0
 * Contact: numax@napicu.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NapicuPocasiResponseModel { 
    name: string;
    country: string;
    pressure: number;
    temp: number;
    temp_min: number;
    temp_max: number;
    feels_like: number;
    humidity: number;
    clouds: number;
    wind_speed: number;
    icon: string;
    description: string;
}

