/**
 * NapicuWebAPI
 * NapicuAPI pro NapicuWebs
 *
 * The version of the OpenAPI document: v2.0
 * Contact: numax@napicu.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NapicuPopJonanekPostModel { 
    counter: number;
}

