/**
 * NapicuAPI
 * API pro NapicuWebs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NapicuPocasiResponseModel { 
    name: string;
    country: string;
    pressure: number;
    temp: number;
    temp_min: number;
    temp_max: number;
    feels_like: number;
    humidity: number;
    clouds: number;
    wind_speed: number;
    icon: string;
    description: string;
}

