export * from './napicuBiosWaitListController.service';
import { NapicuBiosWaitListControllerService } from './napicuBiosWaitListController.service';
export * from './napicuIpController.service';
import { NapicuIpControllerService } from './napicuIpController.service';
export * from './napicuPocasiController.service';
import { NapicuPocasiControllerService } from './napicuPocasiController.service';
export * from './napicuPopJonanekController.service';
import { NapicuPopJonanekControllerService } from './napicuPopJonanekController.service';
export * from './napicuTypeGameController.service';
import { NapicuTypeGameControllerService } from './napicuTypeGameController.service';
export const APIS = [NapicuBiosWaitListControllerService, NapicuIpControllerService, NapicuPocasiControllerService, NapicuPopJonanekControllerService, NapicuTypeGameControllerService];
